env: energy
env_args:
  map_name: "p2p"
  continuous_actions: False
  render_mode: None
  max_cycles: 25

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False
