env: energy
env_args:
  map_name: "p2p"
  max_cycles: 100 
  max_gen_power: 1
  min_gen_power: -1
  max_con_price: 1
  min_con_price: 0.1
  profit_threshold: 500
  max_steps: 100
 
mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False
